name: "Install Flutter"
description: "Install Flutter and get dependencies"

runs:
  using: "composite"
  steps:
    - name: setup
      shell: bash
      run: mise run setup

    # 現在の環境を出力する
    - name: flutter environments
      shell: bash
      run: |
        echo "flutter version: $(flutter --version)"
        echo "flutter path: $(which flutter)"
        echo "dart version: $(dart --version)"
        echo "dart path: $(which dart)"
