name: monolith_define
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/flutter_monolith

environment:
  sdk: ">=3.8.0"

dependencies:
  monolith: ^1.0.0
  armyknife_logger: ^1.0.1
  freezed_annotation: ^3.1.0
  meta: ^1.16.0
  path: ^1.9.1
  dartx: ^1.2.0
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
