name: monolith_runner
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.8.0"

dependencies:
  json_annotation: ^4.9.0
  monolith: ^1.0.0
  monolith_xcodegen: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
