name: monolith_runner
description: A runner package for executing all monolith features from a unified command-line interface. By adding it to dev_dependencies, you can access all monolith functionality through dart run monolith:* commands.
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_monolith

environment:
  sdk: ">=3.8.0"

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  monolith: ^1.0.0
  monolith_define: ^1.0.0
  monolith_install: ^1.0.0
  monolith_localization: ^1.0.0
  monolith_xcodegen: ^1.0.0
  ansicolor: ^2.0.3
  armyknife_logger: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
