name: monolith_install
description: A package that securely deploys files to the workspace from data retrieved from secret management tools such as the op inject command. It integrates with secret management tools like 1Password and AWS Secrets Manager to automate the distribution of sensitive files.
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_monolith

environment:
  sdk: ">=3.8.0"

dependencies:
  monolith: ^1.0.0
  armyknife_logger: ^1.0.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
