name: monolith_localization
description: A package that supports building localization resources on a module basis, which is not provided by Flutter's standard features. It provides a mechanism for each package to independently manage localization resources in large-scale Flutter projects.
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_monolith

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  meta: ^1.16.0
  armyknife_dartx: ^1.0.0
  armyknife_logger: ^1.0.1
  csv: ^6.0.0
  dartx: ^1.2.0
  path: ^1.9.1
  mustache_template: ^2.0.0
  monolith: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
